// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Toy.proto

package com.goody.utils.maojian;

public interface PeopleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.goody.utils.maojian.People)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   *
   * @return The value.
   */
  java.lang.String getValue();

    /**
     * <code>string value = 1;</code>
     *
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
    getValueBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();
}
