// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Toy.proto

package com.goody.utils.maojian;

public final class Toy {
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_com_goody_utils_maojian_People_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_com_goody_utils_maojian_People_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
        descriptor;

  static {
    java.lang.String[] descriptorData = {
        "\n\tToy.proto\022\027com.goody.utils.maojian\"$\n\006" +
            "People\022\r\n\005value\030\001 \001(\t\022\013\n\003age\030\002 \001(\0052Z\n\rPe" +
            "opleService\022I\n\005hello\022\037.com.goody.utils.m" +
            "aojian.People\032\037.com.goody.utils.maojian." +
            "PeopleB \n\027com.goody.utils.maojianB\003ToyP\001" +
            "b\006proto3"
    };
      descriptor = com.google.protobuf.Descriptors.FileDescriptor
          .internalBuildGeneratedFileFrom(descriptorData,
              new com.google.protobuf.Descriptors.FileDescriptor[]{
              });
      internal_static_com_goody_utils_maojian_People_descriptor =
          getDescriptor().getMessageTypes().get(0);
      internal_static_com_goody_utils_maojian_People_fieldAccessorTable = new
          com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
          internal_static_com_goody_utils_maojian_People_descriptor,
          new java.lang.String[]{"Value", "Age",});
  }
  private Toy() {}

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

  // @@protoc_insertion_point(outer_class_scope)
}
